name: Feature Request
description: Suggest a new feature or enhancement for the project
title: "[FEATURE] Short Description of the Feature Request"
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you are requesting.
      placeholder: Describe the feature here...
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain how this feature would benefit the project or users.
      placeholder: Explain the use case...
    validations:
      required: true
  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: Provide any ideas or suggestions for implementing this feature.
      placeholder: Provide implementation ideas...
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the feature request.
      placeholder: Add additional context...
