name: Update vk.xml and Create Pull Request

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

jobs:
  update-vkxml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Latest vk.xml
        run: |
          curl -o latest_vk.xml https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/main/xml/vk.xml

      - name: Compare vk.xml
        id: compare-vkxml
        run: |
          if ! cmp -s latest_vk.xml vk.xml; then
            echo "vk.xml has changed."
            echo "::set-output name=changed::true"
          else
            echo "vk.xml is up to date."
            echo "::set-output name=changed::false"
          fi

      - name: Update vk.xml
        if: steps.compare-vkxml.outputs.changed == 'true'
        run: |
          mv latest_vk.xml vk.xml

      - name: Check branch vkxml-update exists
        if: steps.compare-vkxml.outputs.changed == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
          try {
                        const branches = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/vkxml-update'
            });
            console.log('Branch vkxml-update exists');
          }
          catch (error) {
            if (error.status === 404) {
              console.log('Branch vkxml-update does not exist');
              console.log('::set-output name=branch_exists::false');
            }
            throw error;
          }

      - name: Create Branch vkxml-update if it doesn't exists
        if: steps.compare-vkxml.outputs.changed == 'true' && steps.check-branch-vkxml-update-exists.outputs.branch_exists == 'false'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: branch } = await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/heads/vkxml-update',
              sha: context.sha
            });
            console.log('Branch vkxml-update created');
            console.log('::set-output name=branch_created::true');
      - name: Check if PR exists
        if: steps.compare-vkxml.outputs.changed == 'true' && steps.check-branch-vkxml-update-exists.outputs.branch_exists == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: 'vkxml-update',
              base: 'master'
            });
            if (pullRequests.length > 0) {
              console.log('PR exists');
              console.log('::set-output name=pr_exists::true');
            } else {
              console.log('PR does not exist');
              console.log('::set-output name=pr_exists::false');
            }
      - name: Create PR if it doesn't exists
        if: steps.compare-vkxml.outputs.changed == 'true' && steps.check-branch-vkxml-update-exists.outputs.branch_exists == 'true' && steps.check-if-pr-exists.outputs.pr_exists == 'false'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Update vk.xml',
              head: 'vkxml-update',
              base: 'master',
              body: 'Update vk.xml'
            });
            console.log('PR created');
            console.log('::set-output name=pr_created::true');
