name: Update vk.xml and Create Pull Request

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  update-vkxml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Latest vk.xml
        run: |
          curl -o latest_vk.xml https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/main/xml/vk.xml

      - name: Compare vk.xml
        id: compare-vkxml
        run: |
          if ! cmp -s latest_vk.xml vk.xml; then
            echo "vk.xml has changed."
            echo "::set-output name=changed::true"
          else
            echo "vk.xml is up to date."
            echo "::set-output name=changed::false"
          fi

      - name: Update vk.xml
        if: steps.compare-vkxml.outputs.changed == 'true'
        run: |
          mv latest_vk.xml vk.xml

      - name: Create Pull Request
        if: steps.compare-vkxml.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-vkxml
          commit-message: "Update vk.xml"
          title: "Update vk.xml"
          body: "This pull request updates vk.xml"
          labels: "automated"
          base: master
          files: |
            vk.xml

